name: Code Quality

on: [push]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      database:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRES_USERNAME: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: findafriend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get and setup Node version
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Code format
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Run Tests E2E
        run: npm run test:e2e
        env:
          JWT_SECRET: testing-secret
          DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/findafriend?schema=public"
          APP_URL: http://localhost:3333
